pipeline {
    agent { label 'jenkins-agent' }

    environment {
        DOCKER_USER  = 'marcobuccidev'
        IMAGE_NAME   = 'flask-app-example-build'
        DOCKER_CREDS = 'docker-hub' 
    }

    stages {
        stage('Docker Tag') {
            steps {
                script {
                    def gitSha = env.GIT_COMMIT ? env.GIT_COMMIT.take(7) : 'unknown'

                    if (env.TAG_NAME) {
                        env.IMAGE_TAG = env.TAG_NAME
                    } 
                    else if (env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'main') {
                        env.IMAGE_TAG = 'latest'
                    } 
                    else if (env.BRANCH_NAME == 'develop') {
                        env.IMAGE_TAG = "develop-${gitSha}"
                    } 
                    else {
                        def branchSanitized = env.BRANCH_NAME ? env.BRANCH_NAME.replaceAll('/', '-') : 'build'
                        env.IMAGE_TAG = "${branchSanitized}-${gitSha}"
                    }

                    echo "Tag Docker: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${env.DOCKER_USER}/${env.IMAGE_NAME}:${env.IMAGE_TAG} /home/vagrant"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDS, usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "echo \$PASS | docker login -u \$USER --password-stdin"
                        sh "docker push ${env.DOCKER_USER}/${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                        sh "docker logout"
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                if (env.IMAGE_TAG) {
                    sh "docker rmi ${env.DOCKER_USER}/${env.IMAGE_NAME}:${env.IMAGE_TAG} || true"
                }
            }
        }
    }
}